SkoolWebsite/KlokRooster/urls.py
from django.urls import path
from KlokRooster.views import (Index, RoosterListView, RoosterDetailView,
                                RoosterUpdateView, RoosterCreateView, RoosterDeleteView,
                                luister_vir_lui, verdoof, lui_klok, RoosterLoginView)
from django.contrib.auth.views import LogoutView

app_name = "KlokRooster"

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('teken_in', RoosterLoginView.as_view(), name="login"),
    path('teken_uit', LogoutView.as_view(), name="logout"),
    path('roosterlys/', RoosterListView.as_view(), name="roosterlys"),
    path('rooster/<int:pk>/luisterend', luister_vir_lui, name="luister_vir_lui"),
    path('rooster/<int:pk>/verdoof', verdoof, name="verdoof"),
    path('rooster/<int:pk>/lui_klok', lui_klok, name="lui_klok"),
    path('rooster/<int:pk>/', RoosterDetailView.as_view(), name="rooster"),
    path('rooster/<int:pk>/verander', RoosterUpdateView.as_view(), name="verander_rooster"),
    path('skep_rooster', RoosterCreateView.as_view(), name="skep_rooster"),
    path('rooster/<int:pk>/skrap', RoosterDeleteView.as_view(), name="skrap_rooster"),
]

SkoolWebsite/SkoolWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
import KlokRooster.urls
from KlokRooster.models import Rooster
from django.shortcuts import get_object_or_404

urlpatterns = [
    path('', include(KlokRooster.urls)),
    path('admin/', admin.site.urls),
]

# Insures all roosters are deaf on startup.
rooster_list = Rooster.objects.all()
for rooster in rooster_list:
    rooster.luisterend = False
    rooster.save()

SkoolWebsite/KlokRooster/models.py
from django.db import models
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
import datetime
import time
from playsound import playsound
from pathlib import Path
import os

# Create your models here.
class Rooster(models.Model):
    naam = models.CharField(max_length=256, default="Nuwe Rooster")
    
    aantreetyd = models.TimeField(default="7:20")
    periode1 = models.TimeField(default="7:30")
    periode2 = models.TimeField(default="8:00")
    periode3 = models.TimeField(default="8:30")
    periode4 = models.TimeField(default="9:00")
    pouse1 = models.TimeField(default="9:30")
    periode5 = models.TimeField(default="9:45")
    periode6 = models.TimeField(default="10:15")
    periode7 = models.TimeField(default="10:45")
    periode8 = models.TimeField(default="11:15")
    pouse2 = models.TimeField(default="11:45")
    periode9 = models.TimeField(default="12:00")
    periode10 = models.TimeField(default="12:30")
    periode11 = models.TimeField(default="13:00")
    periode12 = models.TimeField(default="13:30")
    uitkomtyd = models.TimeField(default="14:00")

    luisterend = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse_lazy("KlokRooster:rooster", kwargs={"pk" : self.pk}) 

    def lui_klok(self):
        playsound(os.path.join(Path(__file__).resolve().parent, "static/audio/Skoolklok_audio.m4a"))
        print("Klok lui: " + datetime.datetime.now().strftime("%H:%M:%S"))

    def luister_vir_lui(self, luiTye):
        while get_object_or_404(Rooster, pk=self.pk).luisterend:
            if datetime.datetime.now().strftime("%H:%M:%S") == luiTye[-1]:
                self.lui_klok()  
                print("Stop.")
                break
            if datetime.datetime.now().strftime("%H:%M:%S") in luiTye:
                self.lui_klok()

    def __str__(self):
        return self.naam

SkoolWebsite/KlokRooster/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView, ListView, DetailView
from KlokRooster.models import Rooster
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
import datetime

# Create your views here.
class Index(TemplateView):
    template_name = 'index.html'

class RoosterAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login' : ("Die gegewe besonderhede was ongeldig. Probeer weer of kontak die administrateur."),
        'inactive' : ("Hierdie rekening is tans onaktief.")
    }

    def __init__(self, *args, **kwargs):
        super(RoosterAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields["username"].label = "Noemnaam:"
        self.fields["password"].label = "Wagwoord:"
    
class RoosterLoginView(LoginView):
    template_name = "login.html"
    authentication_form = RoosterAuthenticationForm

class RoosterListView(LoginRequiredMixin, ListView):
    context_object_name = "roosters"
    model = Rooster
    template_name = "roosterlys.html"

@login_required
def luister_vir_lui(request, pk):
    model = get_object_or_404(Rooster, pk=pk)
    model.luisterend = True
    model.save()
    luiTye = [
        model.aantreetyd.strftime("%H:%M:%S"),
        model.periode1.strftime("%H:%M:%S"), 
        model.periode2.strftime("%H:%M:%S"),
        model.periode3.strftime("%H:%M:%S"), 
        model.periode4.strftime("%H:%M:%S"),
        model.pouse1.strftime("%H:%M:%S"),
        model.periode5.strftime("%H:%M:%S"), 
        model.periode6.strftime("%H:%M:%S"), 
        model.periode7.strftime("%H:%M:%S"), 
        model.periode8.strftime("%H:%M:%S"),
        model.pouse2.strftime("%H:%M:%S"), 
        model.periode9.strftime("%H:%M:%S"),
        model.periode10.strftime("%H:%M:%S"), 
        model.periode11.strftime("%H:%M:%S"), 
        model.periode12.strftime("%H:%M:%S"), 
        model.uitkomtyd.strftime("%H:%M:%S")
    ]
    print("Luisterend: " + datetime.datetime.now().strftime("%H:%M:%S"))
    model.luister_vir_lui(luiTye)
    model.luisterend = False
    model.save()
    print("Doof: " + datetime.datetime.now().strftime("%H:%M:%S"))
    return redirect(model.get_absolute_url())

@login_required
def verdoof(request, pk):
    model = get_object_or_404(Rooster, pk=pk)
    model.luisterend = False
    model.save()
    print("Doof: " + datetime.datetime.now().strftime("%H:%M:%S"))
    return redirect(model.get_absolute_url())

@login_required
def lui_klok(request, pk):
    model = get_object_or_404(Rooster, pk=pk)
    model.lui_klok()
    return redirect(model.get_absolute_url())

class RoosterDetailView(LoginRequiredMixin, DetailView):
    context_object_name = "rooster"
    model = Rooster
    template_name = "wys_rooster.html"

class RoosterUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = "rooster"
    model = Rooster
    fields = ("naam", "aantreetyd", "periode1", "periode2", "periode3", "periode4", "pouse1", "periode5", "periode6", "periode7", "periode8", "pouse2", "periode9", "periode10", "periode11", "periode12", "uitkomtyd")
    template_name = "verander_rooster.html"

class RoosterCreateView(LoginRequiredMixin, CreateView):
    model = Rooster
    fields = ("naam", "aantreetyd", "periode1", "periode2", "periode3", "periode4", "pouse1", "periode5", "periode6", "periode7", "periode8", "pouse2", "periode9", "periode10", "periode11", "periode12", "uitkomtyd")
    template_name = "skep_rooster.html"

class RoosterDeleteView(LoginRequiredMixin, DeleteView):
    context_object_name = "rooster"
    model = Rooster
    template_name = "skrap_rooster.html"
    success_url = reverse_lazy("KlokRooster:roosterlys")
    

SkoolWebsite/KlokRooster/templates/index.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<title>Tuisblad</title>
{% endblock %}

{% block body_block %}
<div class="content">
    <br>
    <h1>Welkom by Hardekool Akademie se klok-tuisblad.</h1>
    <img src="{% static 'images/hardekool_logo.jpg' %}" alt="Oops">
</div>
{% endblock %}

SkoolWebsite/KlokRooster/templates/login.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<title>Teken in</title>
{% endblock %}

{% block body_block %}
<br>
<h2>Teken asseblief in om die toepassing te kan gebruik.</h2>
<form action="{% url 'KlokRooster:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="teken_in">Teken in</button>
</form>
{% endblock %}

SkoolWebsite/KlokRooster/templates/rooster_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/Bootstrap/bootstrap-grid.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/Bootstrap/bootstrap-reboot.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/Bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/rooster_base.css' %}">
        <script src="{% static 'js/Bootstrap/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/Bootstrap/bootstrap.bundle.min.js' %}"></script>
        {% block head_block %}
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-custom">
            <a class="navbar-brand navbrand-custom" href="{% url 'KlokRooster:index' %}">HARDEKOOL AKADEMIE</a>
            <div>
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link navlink-custom" href="{% url 'KlokRooster:logout'%}">Teken uit</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle dropdown-toggle-custom" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Wiplys</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'KlokRooster:roosterlys'%}">Roosterlys</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'admin:index'%}">Admin</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link navlink-custom" href="{% url 'KlokRooster:login' %}">Teken in</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle dropdown-toggle-custom" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Wiplys</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'admin:index'%}">Admin</a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}

            {% endblock %}
        </div>       
    </body>
</html>

SkoolWebsite/KlokRooster/templates/roosterlys.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/roosterlys.css' %}">
<title>Roosterlys</title>
{% endblock %}

{% block body_block %}
<br>
<h3><u>Roosters:</u></h3>
<ol>
    {% for rooster in roosters %}
        <li>
            <a class="lys_link" href="{% url 'KlokRooster:rooster' rooster.pk %}">{{ rooster.naam }}</a>
        </li>
    {% endfor %}
</ol>
<br>
<a href="{% url 'KlokRooster:skep_rooster' %}"><button class="skep_nuwe">Skep Nuwe Rooster</button></a>
{% endblock %}

SkoolWebsite/KlokRooster/templates/skep_rooster.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/skep_rooster.css' %}">
<title>Skep Nuwe Rooster</title>
{% endblock %}

{% block body_block %}
<br>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="skep_nuwe" type="submit">Skep Rooster</button>
</form>
<br>
{% endblock %}

SkoolWebsite/KlokRooster/templates/skrap_rooster.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/skrap_rooster.css' %}">
<title>Skrap "{{ rooster.naam }}"</title>
{% endblock %}

{% block body_block %}
<form method="POST">
    {% csrf_token %}
    <br>    
    <h2>Is u seker u wil "{{ rooster.naam }}" SKRAP?</h2>
    <br>
    <button class="skrap" type="submit">SKRAP</button>
    <br>
    <br>
    <a href="{% url 'KlokRooster:roosterlys' %}" id="kanselleer">Kanselleer</a>
</form>
{% endblock %}

SkoolWebsite/KlokRooster/templates/verander_rooster.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/verander_rooster.css' %}">
<title>Verander Rooster: {{ rooster.naam }}</title>
{% endblock %}

{% block body_block %}
<br>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Bevestig</button>
</form>
<br>
{% endblock %}

SkoolWebsite/KlokRooster/templates/wys_rooster.html
{% extends 'rooster_base.html' %}

{% block head_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/wys_rooster.css' %}">
<title>{{ rooster.naam }}</title>
<script>
    function veranderToestand() {
        if (document.getElementById("luister_doof").innerHTML === "<a href=\"{% url 'KlokRooster:verdoof' rooster.pk %}\"><button class=\"luisterend\">Verdoof</button></a>") {
            document.getElementById("luister_doof").innerHTML = "<a href=\"{% url 'KlokRooster:luister_vir_lui' rooster.pk %}\"><button class=\"doof\">Luister</button></a>"
        } else {
            document.getElementById("luister_doof").innerHTML = "<a href=\"{% url 'KlokRooster:verdoof' rooster.pk %}\"><button class=\"luisterend\">Verdoof</button></a>"
        }
}
</script>
{% endblock %}

{% block body_block %}
<br>
<h2>Rooster: {{ rooster.naam }}</h2>
<br>
<table>
    <tr>
        <td><b>Aantreetyd</b></td>
        <td>{{ rooster.aantreetyd }}</td>
    </tr>
    <tr>
        <td><b>Periode 1</b></td>
        <td>{{ rooster.periode1 }}</td>
    </tr>
    <tr>
        <td><b>Periode 2</b></td>
        <td>{{ rooster.periode2 }}</td>
    </tr>
    <tr>
        <td><b>Periode 3</b></td>
        <td>{{ rooster.periode3 }}</td>
    </tr>
    <tr>
        <td><b>Periode 4</b></td>
        <td>{{ rooster.periode4 }}</td>
    </tr>
    <tr>
        <td><b>Pouse 1</b></td>
        <td>{{ rooster.pouse1 }}</td>
    </tr>
    <tr>
        <td><b>Periode 5</b></td>
        <td>{{ rooster.periode5 }}</td>
    </tr>
    <tr>
        <td><b>Periode 6</b></td>
        <td>{{ rooster.periode6 }}</td>
    </tr>
    <tr>
        <td><b>Periode 7</b></td>
        <td>{{ rooster.periode7 }}</td>
    </tr>
    <tr>
        <td><b>Periode 8</b></td>
        <td>{{ rooster.periode8 }}</td>
    </tr>
    <tr>
        <td><b>Pouse 2</b></td>
        <td>{{ rooster.pouse2 }}</td>
    </tr>
    <tr>
        <td><b>Periode 9</b></td>
        <td>{{ rooster.periode9 }}</td>
    </tr>
    <tr>
        <td><b>Periode 10</b></td>
        <td>{{ rooster.periode10 }}</td>
    </tr>
    <tr>
        <td><b>Periode 11</b></td>
        <td>{{ rooster.periode11 }}</td>
    </tr>
    <tr>
        <td><b>Periode 12</b></td>
        <td>{{ rooster.periode12 }}</td>
    </tr>
    <tr>
        <td><b>Uitkomtyd</b></td>
        <td>{{ rooster.uitkomtyd }}</td>
    </tr>
</table>
<br>
<a href="{% url 'KlokRooster:verander_rooster' rooster.pk %}"><button class="verander">Verander</button></a>
<a href="{% url 'KlokRooster:skrap_rooster' rooster.pk %}"><button class="skrap">Skrap</button></a>
<br>
{% if not rooster.luisterend %}
    <div id="luister_doof">
        <a href="{% url 'KlokRooster:luister_vir_lui' rooster.pk %}"><button class="doof" onclick="veranderToestand()">Luister</button></a>
    </div>
{% else %}
    <div id="luister_doof">
        <a href="{% url 'KlokRooster:verdoof' rooster.pk %}"><button class="luisterend">Verdoof</button></a>
    </div>
{% endif %}
<br>
<a href="{% url 'KlokRooster:lui_klok' rooster.pk %}"><button class="lui_klok">Lui Klok</button></a>
{% endblock %}